# Generated by Django 3.0.8 on 2020-07-16 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Eg. 2020-07-16T19:40:02.785988+05:45', verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Eg. 2020-07-16T19:40:02.785988+05:45', verbose_name='Updated Date')),
                ('name', models.CharField(help_text='Eg. Backlog, ToDo, Doing, Research, On hold etc.', max_length=50, verbose_name='Main category of TODO list')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Eg. 2020-07-16T19:40:02.785988+05:45', verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Eg. 2020-07-16T19:40:02.785988+05:45', verbose_name='Updated Date')),
                ('title', models.CharField(help_text='Eg. Integrate login system.', max_length=255, verbose_name='Title of TODO item')),
                ('deadline', models.DateTimeField(blank=True, help_text='Eg. 2020-07-16T19:40:02.785988+05:45', null=True, verbose_name='Deadline of TODO')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
